### PR TITLE
Allow score adjustment by event admins

### PR DESCRIPTION
**Pull request by tabascq**
Allows admins to create invisible puzzles with positive or negative scores, so team scores can be adjusted without affecting puzzle counts.

### CODE REVIEW

**Review by royleban — APPROVED** [review]
Look solid.

**Review by Vroo — APPROVED** [review]
This does what it says it does although this condition 
```
.Where(pspt => pspt.SolvedTime != null && pspt.SolvedTime <= submissionEnd)
```
means that adjustments can only be done before the event ends (or by doing retroactive changes).

**Comment by tabascq** [comment]
I'm fine with needing retroactive changes right now since there's a risk that if we modify the event cutoff, something else will go wrong given the fact that players can solve puzzles after the event is over.

**Comment by royleban** [comment]
I agree with Kenny. But, it might be nice to create a future feature that allows for changing a puzzle's SolvedTime to 1 second before the event ended (or perhaps a specified time) to avoid having to write custom SQL to make retroactive changes.

**Comment by tabascq** [comment]
FYI, this is deployed.

**Pull request merged**
