### PR TITLE
do not send mail to no one #424

### PR DESCRIPTION
**Pull request by Vroo**

### CODE REVIEW

**Comment by royleban** [comment]
See also my different commit for this bug

**Comment by tabascq** [comment]
I think this is a reasonable way to fix the issue, but I do not believe this is a pressing need for PH20 as we're past the point where we'll be updating responses for nobody. I do think we'll want this as Puzzleday and future events ramp up and fill out the database, so I think it's worth taking afterwards. I just won't want the added risk right now.

**Comment by tabascq** [comment]
This change has merge conflicts due to other changes since the PR was created and is now missing a case as a result; I'm going to make a new PR that does roughly the same thing, and put you on it for review.

**Comment by tabascq** [comment]
Closing in favor of #759

**Pull request closed without merging**
